using System;
using System.Collections.Generic;
using System.Text;

namespace IdentityCardInformationExtractor.Enums
{

    /// <summary>
    /// https://gist.github.com/zspine/2365808
    /// </summary>

    /// <summary>
    ///https://en.wikipedia.org/wiki/ISO_3166-1
    /// </summary>
    /// 
    public enum Nationality
    {
        Andorra = 53,
        UnitedArabEmirates = 126,
        Afghanistan = 133,
        Anguilla = 55,
        Armenia = 58,
        Angola = 54,
        Antarctica = 55,
        Argentina = 57,
        Austria = 3,
        Australia = 2,
        Aruba = 59,
        Bangladesh = 45,
        Barbados = 63,
        Belgium = 4,
        Bahrain = 62,
        Bermuda = 67,
        Bolivia = 69,
        Brazil = 43,
        Bahamas = 61,
        Bhutan = 68,
        Bulgaria = 44,
        Belarus = 64,
        Belize = 65,
        Canada = 6,
        Congo = 72,
        China = 51,
        Switzerland = 35,
        Chile = 71,
        Cambodia = 5,
        Cameroon = 70,
        Columbia = 46,
        CzechRepublic = 50,
        CostaRica = 73,
        Cuba = 75,
        Cyprus = 76,
        Germany = 10,
        Denmark = 7,
        Dominica = 77,
        Ecuador = 78,
        Estonia = 79,
        Egypt = 8,
        Ethiopia = 80,
        Finland = 82,
        Fiji = 81,
        France = 9,
        UnitedKingdom = 39,
        Georgia = 83,
        Ghana = 84,
        Guinea = 86,
        Greece = 11,
        Guyana = 87,
        HongKong = 13,
        Croatia = 74,
        Hungary = 14,
        Indonesia = 16,
        Ireland = 90,
        India = 15,
        Iraq = 89,
        Iran = 17,
        Israel = 18,
        Iceland = 88,
        Italy = 19,
        Jamaica = 91,
        Jordan = 92,
        Japan = 20,
        Kenya = 94,
        Korea = 21,
        Kuwait = 95,
        Kazakhstan = 134,
        Kazakchstan = 93,
        Lebanon = 96,
        SriLanka = 33,
        Lithuania = 97,
        Luxembourg = 98,
        Morocco = 104,
        Monaco = 102,
        Mexico = 47,
        Myanmar = 105,
        Mongolia = 103,
        Macau = 42,
        Mauritius = 100,
        Maldives = 99,
        Malaysia = 22,
        Namibia = 106,
        Nigeria = 108,
        Netherland = 12,
        Norway = 24,
        Nepal = 107,
        NewZealand = 23,
        Oman = 109,
        Panama = 110,
        Peru = 112,
        Philippines = 27,
        Pakistan = 26,
        Poland = 28,
        Palestine = 00,
        Portugal = 113,
        Paraguay = 111,
        Qatar = 115,
        Romania = 48,
        Russia = 29,
        SaudiArabia = 116,
        Seychelles = 119,
        Sweden = 34,
        Singapore = 30,
        Slovakia = 120,
        Senegal = 117,
        Somalia = 121,
        Spain = 32,
        Thailand = 37,
        Tunisia = 123,
        Turkey = 38,
        Taiwan = 36,
        Tanzania = 122,
        Ukraine = 125,
        Uganda = 124,
        UnitedStatesOfAmerica = 40,
        Uruguay = 127,
        Uzbekistan = 128,
        Venezuela = 49,
        Vietnam = 1,
        Yemen = 130,
        SouthAfrica = 31,
        Zambia = 131,
        Zimbabwe = 132
    }
}
